// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlzGRBft5O-bakexVsPfY88dwBQNhULJQ',
    appId: '1:224631928411:web:f6717edbd1a0e6e1ab717e',
    messagingSenderId: '224631928411',
    projectId: 'fund-management-app-acf8b',
    authDomain: 'fund-management-app-acf8b.firebaseapp.com',
    storageBucket: 'fund-management-app-acf8b.firebasestorage.app',
    measurementId: 'G-4T410JXZ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1q5uzmsEOCFHsErlBV75PzlaNZUFWyDY',
    appId: '1:224631928411:android:02c4c9dbda5ca80aab717e',
    messagingSenderId: '224631928411',
    projectId: 'fund-management-app-acf8b',
    storageBucket: 'fund-management-app-acf8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCex7n14QfFjmaY9bVitTDTK4W8LC7XQmY',
    appId: '1:224631928411:ios:2007a9e7c6f86251ab717e',
    messagingSenderId: '224631928411',
    projectId: 'fund-management-app-acf8b',
    storageBucket: 'fund-management-app-acf8b.firebasestorage.app',
    iosBundleId: 'com.example.fundManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCex7n14QfFjmaY9bVitTDTK4W8LC7XQmY',
    appId: '1:224631928411:ios:2007a9e7c6f86251ab717e',
    messagingSenderId: '224631928411',
    projectId: 'fund-management-app-acf8b',
    storageBucket: 'fund-management-app-acf8b.firebasestorage.app',
    iosBundleId: 'com.example.fundManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlzGRBft5O-bakexVsPfY88dwBQNhULJQ',
    appId: '1:224631928411:web:0e0f9225dd726d35ab717e',
    messagingSenderId: '224631928411',
    projectId: 'fund-management-app-acf8b',
    authDomain: 'fund-management-app-acf8b.firebaseapp.com',
    storageBucket: 'fund-management-app-acf8b.firebasestorage.app',
    measurementId: 'G-CH7XSDS1NY',
  );
}
